# Generated by Django 4.1.5 on 2023-05-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
